/**
 * generated by Xtext 2.12.0
 */
package org.xtext.selenium.eliedenis.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.selenium.eliedenis.ui.AbstractEDdslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class EDdslUiModule extends AbstractEDdslUiModule {
  public EDdslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
