/**
 * generated by Xtext 2.12.0
 */
package org.xtext.selenium.eliedenis.eDdsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.selenium.eliedenis.eDdsl.ActionNoReturn;
import org.xtext.selenium.eliedenis.eDdsl.EDdslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Action No Return</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ActionNoReturnImpl extends MinimalEObjectImpl.Container implements ActionNoReturn
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ActionNoReturnImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EDdslPackage.Literals.ACTION_NO_RETURN;
  }

} //ActionNoReturnImpl
