/**
 * generated by Xtext 2.12.0
 */
package org.xtext.selenium.eliedenis.eDdsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.selenium.eliedenis.eDdsl.ActionBoolReturn;
import org.xtext.selenium.eliedenis.eDdsl.EDdslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Action Bool Return</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ActionBoolReturnImpl extends MinimalEObjectImpl.Container implements ActionBoolReturn
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ActionBoolReturnImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EDdslPackage.Literals.ACTION_BOOL_RETURN;
  }

} //ActionBoolReturnImpl
