/**
 * generated by Xtext 2.12.0
 */
package org.xtext.selenium.eliedenis.eDdsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.selenium.eliedenis.eDdsl.BoolEnum;
import org.xtext.selenium.eliedenis.eDdsl.BrowserEnum;
import org.xtext.selenium.eliedenis.eDdsl.EDdslPackage;
import org.xtext.selenium.eliedenis.eDdsl.Operation;
import org.xtext.selenium.eliedenis.eDdsl.Series;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Series</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.selenium.eliedenis.eDdsl.impl.SeriesImpl#getBrowser <em>Browser</em>}</li>
 *   <li>{@link org.xtext.selenium.eliedenis.eDdsl.impl.SeriesImpl#getExpectedReturn <em>Expected Return</em>}</li>
 *   <li>{@link org.xtext.selenium.eliedenis.eDdsl.impl.SeriesImpl#getOperations <em>Operations</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SeriesImpl extends MinimalEObjectImpl.Container implements Series
{
  /**
   * The default value of the '{@link #getBrowser() <em>Browser</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBrowser()
   * @generated
   * @ordered
   */
  protected static final BrowserEnum BROWSER_EDEFAULT = BrowserEnum.FIREFOX;

  /**
   * The cached value of the '{@link #getBrowser() <em>Browser</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBrowser()
   * @generated
   * @ordered
   */
  protected BrowserEnum browser = BROWSER_EDEFAULT;

  /**
   * The default value of the '{@link #getExpectedReturn() <em>Expected Return</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpectedReturn()
   * @generated
   * @ordered
   */
  protected static final BoolEnum EXPECTED_RETURN_EDEFAULT = BoolEnum.TRUE;

  /**
   * The cached value of the '{@link #getExpectedReturn() <em>Expected Return</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpectedReturn()
   * @generated
   * @ordered
   */
  protected BoolEnum expectedReturn = EXPECTED_RETURN_EDEFAULT;

  /**
   * The cached value of the '{@link #getOperations() <em>Operations</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperations()
   * @generated
   * @ordered
   */
  protected EList<Operation> operations;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SeriesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EDdslPackage.Literals.SERIES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BrowserEnum getBrowser()
  {
    return browser;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBrowser(BrowserEnum newBrowser)
  {
    BrowserEnum oldBrowser = browser;
    browser = newBrowser == null ? BROWSER_EDEFAULT : newBrowser;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EDdslPackage.SERIES__BROWSER, oldBrowser, browser));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BoolEnum getExpectedReturn()
  {
    return expectedReturn;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExpectedReturn(BoolEnum newExpectedReturn)
  {
    BoolEnum oldExpectedReturn = expectedReturn;
    expectedReturn = newExpectedReturn == null ? EXPECTED_RETURN_EDEFAULT : newExpectedReturn;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EDdslPackage.SERIES__EXPECTED_RETURN, oldExpectedReturn, expectedReturn));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Operation> getOperations()
  {
    if (operations == null)
    {
      operations = new EObjectContainmentEList<Operation>(Operation.class, this, EDdslPackage.SERIES__OPERATIONS);
    }
    return operations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EDdslPackage.SERIES__OPERATIONS:
        return ((InternalEList<?>)getOperations()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EDdslPackage.SERIES__BROWSER:
        return getBrowser();
      case EDdslPackage.SERIES__EXPECTED_RETURN:
        return getExpectedReturn();
      case EDdslPackage.SERIES__OPERATIONS:
        return getOperations();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EDdslPackage.SERIES__BROWSER:
        setBrowser((BrowserEnum)newValue);
        return;
      case EDdslPackage.SERIES__EXPECTED_RETURN:
        setExpectedReturn((BoolEnum)newValue);
        return;
      case EDdslPackage.SERIES__OPERATIONS:
        getOperations().clear();
        getOperations().addAll((Collection<? extends Operation>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EDdslPackage.SERIES__BROWSER:
        setBrowser(BROWSER_EDEFAULT);
        return;
      case EDdslPackage.SERIES__EXPECTED_RETURN:
        setExpectedReturn(EXPECTED_RETURN_EDEFAULT);
        return;
      case EDdslPackage.SERIES__OPERATIONS:
        getOperations().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EDdslPackage.SERIES__BROWSER:
        return browser != BROWSER_EDEFAULT;
      case EDdslPackage.SERIES__EXPECTED_RETURN:
        return expectedReturn != EXPECTED_RETURN_EDEFAULT;
      case EDdslPackage.SERIES__OPERATIONS:
        return operations != null && !operations.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (browser: ");
    result.append(browser);
    result.append(", expectedReturn: ");
    result.append(expectedReturn);
    result.append(')');
    return result.toString();
  }

} //SeriesImpl
