/**
 * generated by Xtext 2.12.0
 */
package org.xtext.selenium.eliedenis.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.selenium.eliedenis.EDdslRuntimeModule;
import org.xtext.selenium.eliedenis.EDdslStandaloneSetup;
import org.xtext.selenium.eliedenis.ide.EDdslIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class EDdslIdeSetup extends EDdslStandaloneSetup {
  @Override
  public Injector createInjector() {
    EDdslRuntimeModule _eDdslRuntimeModule = new EDdslRuntimeModule();
    EDdslIdeModule _eDdslIdeModule = new EDdslIdeModule();
    return Guice.createInjector(Modules2.mixin(_eDdslRuntimeModule, _eDdslIdeModule));
  }
}
