/**
 * generated by Xtext 2.12.0
 */
package org.xtext.selenium.eliedenis.eDdsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action No Return</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.selenium.eliedenis.eDdsl.EDdslPackage#getActionNoReturn()
 * @model
 * @generated
 */
public interface ActionNoReturn extends EObject
{
} // ActionNoReturn
