/**
 * generated by Xtext 2.12.0
 */
package org.xtext.selenium.eliedenis.eDdsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>All</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.selenium.eliedenis.eDdsl.All#getOperation <em>Operation</em>}</li>
 * </ul>
 *
 * @see org.xtext.selenium.eliedenis.eDdsl.EDdslPackage#getAll()
 * @model
 * @generated
 */
public interface All extends ActionNoReturn
{
  /**
   * Returns the value of the '<em><b>Operation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operation</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation</em>' containment reference.
   * @see #setOperation(ActionNoReturn)
   * @see org.xtext.selenium.eliedenis.eDdsl.EDdslPackage#getAll_Operation()
   * @model containment="true"
   * @generated
   */
  ActionNoReturn getOperation();

  /**
   * Sets the value of the '{@link org.xtext.selenium.eliedenis.eDdsl.All#getOperation <em>Operation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation</em>' containment reference.
   * @see #getOperation()
   * @generated
   */
  void setOperation(ActionNoReturn value);

} // All
