/**
 * generated by Xtext 2.12.0
 */
package org.xtext.selenium.eliedenis.eDdsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.selenium.eliedenis.eDdsl.Constraint#getReadableElement <em>Readable Element</em>}</li>
 *   <li>{@link org.xtext.selenium.eliedenis.eDdsl.Constraint#getConstraintType <em>Constraint Type</em>}</li>
 *   <li>{@link org.xtext.selenium.eliedenis.eDdsl.Constraint#getExpectedVal <em>Expected Val</em>}</li>
 *   <li>{@link org.xtext.selenium.eliedenis.eDdsl.Constraint#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see org.xtext.selenium.eliedenis.eDdsl.EDdslPackage#getConstraint()
 * @model
 * @generated
 */
public interface Constraint extends ActionBoolReturn
{
  /**
   * Returns the value of the '<em><b>Readable Element</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.selenium.eliedenis.eDdsl.ReadableEnum}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Readable Element</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Readable Element</em>' attribute.
   * @see org.xtext.selenium.eliedenis.eDdsl.ReadableEnum
   * @see #setReadableElement(ReadableEnum)
   * @see org.xtext.selenium.eliedenis.eDdsl.EDdslPackage#getConstraint_ReadableElement()
   * @model
   * @generated
   */
  ReadableEnum getReadableElement();

  /**
   * Sets the value of the '{@link org.xtext.selenium.eliedenis.eDdsl.Constraint#getReadableElement <em>Readable Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Readable Element</em>' attribute.
   * @see org.xtext.selenium.eliedenis.eDdsl.ReadableEnum
   * @see #getReadableElement()
   * @generated
   */
  void setReadableElement(ReadableEnum value);

  /**
   * Returns the value of the '<em><b>Constraint Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.selenium.eliedenis.eDdsl.ConstraintTypeEnum}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constraint Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraint Type</em>' attribute.
   * @see org.xtext.selenium.eliedenis.eDdsl.ConstraintTypeEnum
   * @see #setConstraintType(ConstraintTypeEnum)
   * @see org.xtext.selenium.eliedenis.eDdsl.EDdslPackage#getConstraint_ConstraintType()
   * @model
   * @generated
   */
  ConstraintTypeEnum getConstraintType();

  /**
   * Sets the value of the '{@link org.xtext.selenium.eliedenis.eDdsl.Constraint#getConstraintType <em>Constraint Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constraint Type</em>' attribute.
   * @see org.xtext.selenium.eliedenis.eDdsl.ConstraintTypeEnum
   * @see #getConstraintType()
   * @generated
   */
  void setConstraintType(ConstraintTypeEnum value);

  /**
   * Returns the value of the '<em><b>Expected Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expected Val</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expected Val</em>' containment reference.
   * @see #setExpectedVal(Val)
   * @see org.xtext.selenium.eliedenis.eDdsl.EDdslPackage#getConstraint_ExpectedVal()
   * @model containment="true"
   * @generated
   */
  Val getExpectedVal();

  /**
   * Sets the value of the '{@link org.xtext.selenium.eliedenis.eDdsl.Constraint#getExpectedVal <em>Expected Val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expected Val</em>' containment reference.
   * @see #getExpectedVal()
   * @generated
   */
  void setExpectedVal(Val value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameters</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference.
   * @see #setParameters(Parameters)
   * @see org.xtext.selenium.eliedenis.eDdsl.EDdslPackage#getConstraint_Parameters()
   * @model containment="true"
   * @generated
   */
  Parameters getParameters();

  /**
   * Sets the value of the '{@link org.xtext.selenium.eliedenis.eDdsl.Constraint#getParameters <em>Parameters</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameters</em>' containment reference.
   * @see #getParameters()
   * @generated
   */
  void setParameters(Parameters value);

} // Constraint
