/**
 * generated by Xtext 2.12.0
 */
package org.xtext.selenium.eliedenis.eDdsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.selenium.eliedenis.eDdsl.EDdslFactory
 * @model kind="package"
 * @generated
 */
public interface EDdslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "eDdsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/selenium/eliedenis/EDdsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "eDdsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  EDdslPackage eINSTANCE = org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.ModelImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Model</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__MODEL = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.OperationImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 12;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ActionNoReturnImpl <em>Action No Return</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.ActionNoReturnImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getActionNoReturn()
   * @generated
   */
  int ACTION_NO_RETURN = 1;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_NO_RETURN__ACTION = OPERATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Action No Return</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_NO_RETURN_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ActionReturnImpl <em>Action Return</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.ActionReturnImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getActionReturn()
   * @generated
   */
  int ACTION_RETURN = 2;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_RETURN__ACTION = 0;

  /**
   * The number of structural features of the '<em>Action Return</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_RETURN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ActionBoolReturnImpl <em>Action Bool Return</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.ActionBoolReturnImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getActionBoolReturn()
   * @generated
   */
  int ACTION_BOOL_RETURN = 3;

  /**
   * The number of structural features of the '<em>Action Bool Return</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_BOOL_RETURN_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.AllImpl <em>All</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.AllImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getAll()
   * @generated
   */
  int ALL = 4;

  /**
   * The feature id for the '<em><b>Operation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL__OPERATION = 0;

  /**
   * The number of structural features of the '<em>All</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.AttributeImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 5;

  /**
   * The feature id for the '<em><b>Attribute Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__ATTRIBUTE_NAME = 0;

  /**
   * The feature id for the '<em><b>Attribute Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__ATTRIBUTE_VALUE = 1;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.BrowseImpl <em>Browse</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.BrowseImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getBrowse()
   * @generated
   */
  int BROWSE = 6;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROWSE__URL = 0;

  /**
   * The number of structural features of the '<em>Browse</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROWSE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.CheckImpl <em>Check</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.CheckImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getCheck()
   * @generated
   */
  int CHECK = 7;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__ACTION = 0;

  /**
   * The number of structural features of the '<em>Check</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ComparisonImpl <em>Comparison</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.ComparisonImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getComparison()
   * @generated
   */
  int COMPARISON = 8;

  /**
   * The feature id for the '<em><b>First Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__FIRST_VAL = ACTION_BOOL_RETURN_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Comparator Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__COMPARATOR_OPERATOR = ACTION_BOOL_RETURN_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Second Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__SECOND_VAL = ACTION_BOOL_RETURN_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Comparison</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_FEATURE_COUNT = ACTION_BOOL_RETURN_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ConstraintImpl <em>Constraint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.ConstraintImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getConstraint()
   * @generated
   */
  int CONSTRAINT = 9;

  /**
   * The feature id for the '<em><b>Readable Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT__READABLE_ELEMENT = ACTION_BOOL_RETURN_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Constraint Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT__CONSTRAINT_TYPE = ACTION_BOOL_RETURN_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Expected Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT__EXPECTED_VAL = ACTION_BOOL_RETURN_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT__PARAMETERS = ACTION_BOOL_RETURN_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Constraint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT_FEATURE_COUNT = ACTION_BOOL_RETURN_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.CountImpl <em>Count</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.CountImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getCount()
   * @generated
   */
  int COUNT = 10;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNT__PARAMETERS = 0;

  /**
   * The number of structural features of the '<em>Count</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ClickImpl <em>Click</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.ClickImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getClick()
   * @generated
   */
  int CLICK = 11;

  /**
   * The feature id for the '<em><b>Clickable Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__CLICKABLE_ELEMENT = 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__PARAMETERS = 1;

  /**
   * The number of structural features of the '<em>Click</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.ParameterImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 13;

  /**
   * The feature id for the '<em><b>Parameter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__PARAMETER = 0;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ParametersImpl <em>Parameters</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.ParametersImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getParameters()
   * @generated
   */
  int PARAMETERS = 14;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETERS__PARAMETERS = 0;

  /**
   * The number of structural features of the '<em>Parameters</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETERS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ReadImpl <em>Read</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.ReadImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getRead()
   * @generated
   */
  int READ = 15;

  /**
   * The feature id for the '<em><b>Readable Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ__READABLE_ELEMENT = 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ__PARAMETERS = 1;

  /**
   * The number of structural features of the '<em>Read</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.SeriesImpl <em>Series</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.SeriesImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getSeries()
   * @generated
   */
  int SERIES = 16;

  /**
   * The feature id for the '<em><b>Browser</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERIES__BROWSER = 0;

  /**
   * The feature id for the '<em><b>Expected Return</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERIES__EXPECTED_RETURN = 1;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERIES__OPERATIONS = 2;

  /**
   * The number of structural features of the '<em>Series</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERIES_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.TypeImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getType()
   * @generated
   */
  int TYPE = 17;

  /**
   * The feature id for the '<em><b>Text To Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__TEXT_TO_TYPE = 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__PARAMETERS = 1;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ValImpl <em>Val</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.ValImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getVal()
   * @generated
   */
  int VAL = 18;

  /**
   * The feature id for the '<em><b>Bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAL__BOOL = 0;

  /**
   * The number of structural features of the '<em>Val</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ValueImpl <em>Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.ValueImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getValue()
   * @generated
   */
  int VALUE = 19;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.VariableGetImpl <em>Variable Get</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.VariableGetImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getVariableGet()
   * @generated
   */
  int VARIABLE_GET = 20;

  /**
   * The feature id for the '<em><b>Bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_GET__BOOL = VAL__BOOL;

  /**
   * The feature id for the '<em><b>Var Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_GET__VAR_NAME = VAL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable Get</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_GET_FEATURE_COUNT = VAL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.VariableSetImpl <em>Variable Set</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.VariableSetImpl
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getVariableSet()
   * @generated
   */
  int VARIABLE_SET = 21;

  /**
   * The feature id for the '<em><b>Var Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_SET__VAR_NAME = 0;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_SET__ACTION = 1;

  /**
   * The number of structural features of the '<em>Variable Set</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_SET_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.BoolEnum <em>Bool Enum</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.BoolEnum
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getBoolEnum()
   * @generated
   */
  int BOOL_ENUM = 22;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.BrowserEnum <em>Browser Enum</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.BrowserEnum
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getBrowserEnum()
   * @generated
   */
  int BROWSER_ENUM = 23;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.ClickableEnum <em>Clickable Enum</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.ClickableEnum
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getClickableEnum()
   * @generated
   */
  int CLICKABLE_ENUM = 24;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.ComparisonOperatorEnum <em>Comparison Operator Enum</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.ComparisonOperatorEnum
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getComparisonOperatorEnum()
   * @generated
   */
  int COMPARISON_OPERATOR_ENUM = 25;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.ConstraintTypeEnum <em>Constraint Type Enum</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.ConstraintTypeEnum
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getConstraintTypeEnum()
   * @generated
   */
  int CONSTRAINT_TYPE_ENUM = 26;

  /**
   * The meta object id for the '{@link org.xtext.selenium.eliedenis.eDdsl.ReadableEnum <em>Readable Enum</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.selenium.eliedenis.eDdsl.ReadableEnum
   * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getReadableEnum()
   * @generated
   */
  int READABLE_ENUM = 27;


  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.selenium.eliedenis.eDdsl.Model#getModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Model</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Model#getModel()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Model();

  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.ActionNoReturn <em>Action No Return</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action No Return</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.ActionNoReturn
   * @generated
   */
  EClass getActionNoReturn();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.selenium.eliedenis.eDdsl.ActionNoReturn#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Action</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.ActionNoReturn#getAction()
   * @see #getActionNoReturn()
   * @generated
   */
  EReference getActionNoReturn_Action();

  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.ActionReturn <em>Action Return</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action Return</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.ActionReturn
   * @generated
   */
  EClass getActionReturn();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.selenium.eliedenis.eDdsl.ActionReturn#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Action</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.ActionReturn#getAction()
   * @see #getActionReturn()
   * @generated
   */
  EReference getActionReturn_Action();

  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.ActionBoolReturn <em>Action Bool Return</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action Bool Return</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.ActionBoolReturn
   * @generated
   */
  EClass getActionBoolReturn();

  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.All <em>All</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>All</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.All
   * @generated
   */
  EClass getAll();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.selenium.eliedenis.eDdsl.All#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operation</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.All#getOperation()
   * @see #getAll()
   * @generated
   */
  EReference getAll_Operation();

  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.selenium.eliedenis.eDdsl.Attribute#getAttributeName <em>Attribute Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attribute Name</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Attribute#getAttributeName()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_AttributeName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.selenium.eliedenis.eDdsl.Attribute#getAttributeValue <em>Attribute Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attribute Value</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Attribute#getAttributeValue()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_AttributeValue();

  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.Browse <em>Browse</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Browse</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Browse
   * @generated
   */
  EClass getBrowse();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.selenium.eliedenis.eDdsl.Browse#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Browse#getUrl()
   * @see #getBrowse()
   * @generated
   */
  EAttribute getBrowse_Url();

  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.Check <em>Check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Check</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Check
   * @generated
   */
  EClass getCheck();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.selenium.eliedenis.eDdsl.Check#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Action</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Check#getAction()
   * @see #getCheck()
   * @generated
   */
  EReference getCheck_Action();

  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.Comparison <em>Comparison</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comparison</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Comparison
   * @generated
   */
  EClass getComparison();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.selenium.eliedenis.eDdsl.Comparison#getFirstVal <em>First Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>First Val</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Comparison#getFirstVal()
   * @see #getComparison()
   * @generated
   */
  EReference getComparison_FirstVal();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.selenium.eliedenis.eDdsl.Comparison#getComparatorOperator <em>Comparator Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comparator Operator</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Comparison#getComparatorOperator()
   * @see #getComparison()
   * @generated
   */
  EAttribute getComparison_ComparatorOperator();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.selenium.eliedenis.eDdsl.Comparison#getSecondVal <em>Second Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Second Val</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Comparison#getSecondVal()
   * @see #getComparison()
   * @generated
   */
  EReference getComparison_SecondVal();

  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.Constraint <em>Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constraint</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Constraint
   * @generated
   */
  EClass getConstraint();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.selenium.eliedenis.eDdsl.Constraint#getReadableElement <em>Readable Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Readable Element</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Constraint#getReadableElement()
   * @see #getConstraint()
   * @generated
   */
  EAttribute getConstraint_ReadableElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.selenium.eliedenis.eDdsl.Constraint#getConstraintType <em>Constraint Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Constraint Type</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Constraint#getConstraintType()
   * @see #getConstraint()
   * @generated
   */
  EAttribute getConstraint_ConstraintType();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.selenium.eliedenis.eDdsl.Constraint#getExpectedVal <em>Expected Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expected Val</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Constraint#getExpectedVal()
   * @see #getConstraint()
   * @generated
   */
  EReference getConstraint_ExpectedVal();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.selenium.eliedenis.eDdsl.Constraint#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parameters</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Constraint#getParameters()
   * @see #getConstraint()
   * @generated
   */
  EReference getConstraint_Parameters();

  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.Count <em>Count</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Count</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Count
   * @generated
   */
  EClass getCount();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.selenium.eliedenis.eDdsl.Count#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parameters</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Count#getParameters()
   * @see #getCount()
   * @generated
   */
  EReference getCount_Parameters();

  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.Click <em>Click</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Click
   * @generated
   */
  EClass getClick();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.selenium.eliedenis.eDdsl.Click#getClickableElement <em>Clickable Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Clickable Element</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Click#getClickableElement()
   * @see #getClick()
   * @generated
   */
  EAttribute getClick_ClickableElement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.selenium.eliedenis.eDdsl.Click#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parameters</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Click#getParameters()
   * @see #getClick()
   * @generated
   */
  EReference getClick_Parameters();

  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.selenium.eliedenis.eDdsl.Parameter#getParameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parameter</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Parameter#getParameter()
   * @see #getParameter()
   * @generated
   */
  EReference getParameter_Parameter();

  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.Parameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameters</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Parameters
   * @generated
   */
  EClass getParameters();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.selenium.eliedenis.eDdsl.Parameters#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Parameters#getParameters()
   * @see #getParameters()
   * @generated
   */
  EReference getParameters_Parameters();

  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.Read <em>Read</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Read</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Read
   * @generated
   */
  EClass getRead();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.selenium.eliedenis.eDdsl.Read#getReadableElement <em>Readable Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Readable Element</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Read#getReadableElement()
   * @see #getRead()
   * @generated
   */
  EAttribute getRead_ReadableElement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.selenium.eliedenis.eDdsl.Read#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parameters</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Read#getParameters()
   * @see #getRead()
   * @generated
   */
  EReference getRead_Parameters();

  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.Series <em>Series</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Series</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Series
   * @generated
   */
  EClass getSeries();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.selenium.eliedenis.eDdsl.Series#getBrowser <em>Browser</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Browser</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Series#getBrowser()
   * @see #getSeries()
   * @generated
   */
  EAttribute getSeries_Browser();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.selenium.eliedenis.eDdsl.Series#getExpectedReturn <em>Expected Return</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Expected Return</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Series#getExpectedReturn()
   * @see #getSeries()
   * @generated
   */
  EAttribute getSeries_ExpectedReturn();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.selenium.eliedenis.eDdsl.Series#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Series#getOperations()
   * @see #getSeries()
   * @generated
   */
  EReference getSeries_Operations();

  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.selenium.eliedenis.eDdsl.Type#getTextToType <em>Text To Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text To Type</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Type#getTextToType()
   * @see #getType()
   * @generated
   */
  EReference getType_TextToType();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.selenium.eliedenis.eDdsl.Type#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parameters</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Type#getParameters()
   * @see #getType()
   * @generated
   */
  EReference getType_Parameters();

  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.Val <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Val</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Val
   * @generated
   */
  EClass getVal();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.selenium.eliedenis.eDdsl.Val#getBool <em>Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bool</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Val#getBool()
   * @see #getVal()
   * @generated
   */
  EAttribute getVal_Bool();

  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.Value <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Value
   * @generated
   */
  EClass getValue();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.selenium.eliedenis.eDdsl.Value#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.Value#getValue()
   * @see #getValue()
   * @generated
   */
  EReference getValue_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.VariableGet <em>Variable Get</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Get</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.VariableGet
   * @generated
   */
  EClass getVariableGet();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.selenium.eliedenis.eDdsl.VariableGet#getVarName <em>Var Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var Name</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.VariableGet#getVarName()
   * @see #getVariableGet()
   * @generated
   */
  EAttribute getVariableGet_VarName();

  /**
   * Returns the meta object for class '{@link org.xtext.selenium.eliedenis.eDdsl.VariableSet <em>Variable Set</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Set</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.VariableSet
   * @generated
   */
  EClass getVariableSet();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.selenium.eliedenis.eDdsl.VariableSet#getVarName <em>Var Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var Name</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.VariableSet#getVarName()
   * @see #getVariableSet()
   * @generated
   */
  EAttribute getVariableSet_VarName();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.selenium.eliedenis.eDdsl.VariableSet#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Action</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.VariableSet#getAction()
   * @see #getVariableSet()
   * @generated
   */
  EReference getVariableSet_Action();

  /**
   * Returns the meta object for enum '{@link org.xtext.selenium.eliedenis.eDdsl.BoolEnum <em>Bool Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Bool Enum</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.BoolEnum
   * @generated
   */
  EEnum getBoolEnum();

  /**
   * Returns the meta object for enum '{@link org.xtext.selenium.eliedenis.eDdsl.BrowserEnum <em>Browser Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Browser Enum</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.BrowserEnum
   * @generated
   */
  EEnum getBrowserEnum();

  /**
   * Returns the meta object for enum '{@link org.xtext.selenium.eliedenis.eDdsl.ClickableEnum <em>Clickable Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Clickable Enum</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.ClickableEnum
   * @generated
   */
  EEnum getClickableEnum();

  /**
   * Returns the meta object for enum '{@link org.xtext.selenium.eliedenis.eDdsl.ComparisonOperatorEnum <em>Comparison Operator Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Comparison Operator Enum</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.ComparisonOperatorEnum
   * @generated
   */
  EEnum getComparisonOperatorEnum();

  /**
   * Returns the meta object for enum '{@link org.xtext.selenium.eliedenis.eDdsl.ConstraintTypeEnum <em>Constraint Type Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Constraint Type Enum</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.ConstraintTypeEnum
   * @generated
   */
  EEnum getConstraintTypeEnum();

  /**
   * Returns the meta object for enum '{@link org.xtext.selenium.eliedenis.eDdsl.ReadableEnum <em>Readable Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Readable Enum</em>'.
   * @see org.xtext.selenium.eliedenis.eDdsl.ReadableEnum
   * @generated
   */
  EEnum getReadableEnum();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  EDdslFactory getEDdslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.ModelImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Model</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__MODEL = eINSTANCE.getModel_Model();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ActionNoReturnImpl <em>Action No Return</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.ActionNoReturnImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getActionNoReturn()
     * @generated
     */
    EClass ACTION_NO_RETURN = eINSTANCE.getActionNoReturn();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION_NO_RETURN__ACTION = eINSTANCE.getActionNoReturn_Action();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ActionReturnImpl <em>Action Return</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.ActionReturnImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getActionReturn()
     * @generated
     */
    EClass ACTION_RETURN = eINSTANCE.getActionReturn();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION_RETURN__ACTION = eINSTANCE.getActionReturn_Action();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ActionBoolReturnImpl <em>Action Bool Return</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.ActionBoolReturnImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getActionBoolReturn()
     * @generated
     */
    EClass ACTION_BOOL_RETURN = eINSTANCE.getActionBoolReturn();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.AllImpl <em>All</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.AllImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getAll()
     * @generated
     */
    EClass ALL = eINSTANCE.getAll();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALL__OPERATION = eINSTANCE.getAll_Operation();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.AttributeImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Attribute Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__ATTRIBUTE_NAME = eINSTANCE.getAttribute_AttributeName();

    /**
     * The meta object literal for the '<em><b>Attribute Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__ATTRIBUTE_VALUE = eINSTANCE.getAttribute_AttributeValue();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.BrowseImpl <em>Browse</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.BrowseImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getBrowse()
     * @generated
     */
    EClass BROWSE = eINSTANCE.getBrowse();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BROWSE__URL = eINSTANCE.getBrowse_Url();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.CheckImpl <em>Check</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.CheckImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getCheck()
     * @generated
     */
    EClass CHECK = eINSTANCE.getCheck();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECK__ACTION = eINSTANCE.getCheck_Action();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ComparisonImpl <em>Comparison</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.ComparisonImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getComparison()
     * @generated
     */
    EClass COMPARISON = eINSTANCE.getComparison();

    /**
     * The meta object literal for the '<em><b>First Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARISON__FIRST_VAL = eINSTANCE.getComparison_FirstVal();

    /**
     * The meta object literal for the '<em><b>Comparator Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARISON__COMPARATOR_OPERATOR = eINSTANCE.getComparison_ComparatorOperator();

    /**
     * The meta object literal for the '<em><b>Second Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARISON__SECOND_VAL = eINSTANCE.getComparison_SecondVal();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ConstraintImpl <em>Constraint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.ConstraintImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getConstraint()
     * @generated
     */
    EClass CONSTRAINT = eINSTANCE.getConstraint();

    /**
     * The meta object literal for the '<em><b>Readable Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTRAINT__READABLE_ELEMENT = eINSTANCE.getConstraint_ReadableElement();

    /**
     * The meta object literal for the '<em><b>Constraint Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTRAINT__CONSTRAINT_TYPE = eINSTANCE.getConstraint_ConstraintType();

    /**
     * The meta object literal for the '<em><b>Expected Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTRAINT__EXPECTED_VAL = eINSTANCE.getConstraint_ExpectedVal();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTRAINT__PARAMETERS = eINSTANCE.getConstraint_Parameters();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.CountImpl <em>Count</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.CountImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getCount()
     * @generated
     */
    EClass COUNT = eINSTANCE.getCount();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COUNT__PARAMETERS = eINSTANCE.getCount_Parameters();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ClickImpl <em>Click</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.ClickImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getClick()
     * @generated
     */
    EClass CLICK = eINSTANCE.getClick();

    /**
     * The meta object literal for the '<em><b>Clickable Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK__CLICKABLE_ELEMENT = eINSTANCE.getClick_ClickableElement();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLICK__PARAMETERS = eINSTANCE.getClick_Parameters();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.OperationImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.ParameterImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Parameter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER__PARAMETER = eINSTANCE.getParameter_Parameter();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ParametersImpl <em>Parameters</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.ParametersImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getParameters()
     * @generated
     */
    EClass PARAMETERS = eINSTANCE.getParameters();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETERS__PARAMETERS = eINSTANCE.getParameters_Parameters();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ReadImpl <em>Read</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.ReadImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getRead()
     * @generated
     */
    EClass READ = eINSTANCE.getRead();

    /**
     * The meta object literal for the '<em><b>Readable Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute READ__READABLE_ELEMENT = eINSTANCE.getRead_ReadableElement();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference READ__PARAMETERS = eINSTANCE.getRead_Parameters();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.SeriesImpl <em>Series</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.SeriesImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getSeries()
     * @generated
     */
    EClass SERIES = eINSTANCE.getSeries();

    /**
     * The meta object literal for the '<em><b>Browser</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERIES__BROWSER = eINSTANCE.getSeries_Browser();

    /**
     * The meta object literal for the '<em><b>Expected Return</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERIES__EXPECTED_RETURN = eINSTANCE.getSeries_ExpectedReturn();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERIES__OPERATIONS = eINSTANCE.getSeries_Operations();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.TypeImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Text To Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE__TEXT_TO_TYPE = eINSTANCE.getType_TextToType();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE__PARAMETERS = eINSTANCE.getType_Parameters();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ValImpl <em>Val</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.ValImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getVal()
     * @generated
     */
    EClass VAL = eINSTANCE.getVal();

    /**
     * The meta object literal for the '<em><b>Bool</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAL__BOOL = eINSTANCE.getVal_Bool();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.ValueImpl <em>Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.ValueImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getValue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VALUE__VALUE = eINSTANCE.getValue_Value();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.VariableGetImpl <em>Variable Get</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.VariableGetImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getVariableGet()
     * @generated
     */
    EClass VARIABLE_GET = eINSTANCE.getVariableGet();

    /**
     * The meta object literal for the '<em><b>Var Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_GET__VAR_NAME = eINSTANCE.getVariableGet_VarName();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.impl.VariableSetImpl <em>Variable Set</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.VariableSetImpl
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getVariableSet()
     * @generated
     */
    EClass VARIABLE_SET = eINSTANCE.getVariableSet();

    /**
     * The meta object literal for the '<em><b>Var Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_SET__VAR_NAME = eINSTANCE.getVariableSet_VarName();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_SET__ACTION = eINSTANCE.getVariableSet_Action();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.BoolEnum <em>Bool Enum</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.BoolEnum
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getBoolEnum()
     * @generated
     */
    EEnum BOOL_ENUM = eINSTANCE.getBoolEnum();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.BrowserEnum <em>Browser Enum</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.BrowserEnum
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getBrowserEnum()
     * @generated
     */
    EEnum BROWSER_ENUM = eINSTANCE.getBrowserEnum();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.ClickableEnum <em>Clickable Enum</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.ClickableEnum
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getClickableEnum()
     * @generated
     */
    EEnum CLICKABLE_ENUM = eINSTANCE.getClickableEnum();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.ComparisonOperatorEnum <em>Comparison Operator Enum</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.ComparisonOperatorEnum
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getComparisonOperatorEnum()
     * @generated
     */
    EEnum COMPARISON_OPERATOR_ENUM = eINSTANCE.getComparisonOperatorEnum();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.ConstraintTypeEnum <em>Constraint Type Enum</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.ConstraintTypeEnum
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getConstraintTypeEnum()
     * @generated
     */
    EEnum CONSTRAINT_TYPE_ENUM = eINSTANCE.getConstraintTypeEnum();

    /**
     * The meta object literal for the '{@link org.xtext.selenium.eliedenis.eDdsl.ReadableEnum <em>Readable Enum</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.selenium.eliedenis.eDdsl.ReadableEnum
     * @see org.xtext.selenium.eliedenis.eDdsl.impl.EDdslPackageImpl#getReadableEnum()
     * @generated
     */
    EEnum READABLE_ENUM = eINSTANCE.getReadableEnum();

  }

} //EDdslPackage
