/**
 * generated by Xtext 2.12.0
 */
package org.xtext.selenium.eliedenis.eDdsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Read</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.selenium.eliedenis.eDdsl.Read#getReadableElement <em>Readable Element</em>}</li>
 *   <li>{@link org.xtext.selenium.eliedenis.eDdsl.Read#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see org.xtext.selenium.eliedenis.eDdsl.EDdslPackage#getRead()
 * @model
 * @generated
 */
public interface Read extends ActionReturn
{
  /**
   * Returns the value of the '<em><b>Readable Element</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.selenium.eliedenis.eDdsl.ReadableEnum}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Readable Element</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Readable Element</em>' attribute.
   * @see org.xtext.selenium.eliedenis.eDdsl.ReadableEnum
   * @see #setReadableElement(ReadableEnum)
   * @see org.xtext.selenium.eliedenis.eDdsl.EDdslPackage#getRead_ReadableElement()
   * @model
   * @generated
   */
  ReadableEnum getReadableElement();

  /**
   * Sets the value of the '{@link org.xtext.selenium.eliedenis.eDdsl.Read#getReadableElement <em>Readable Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Readable Element</em>' attribute.
   * @see org.xtext.selenium.eliedenis.eDdsl.ReadableEnum
   * @see #getReadableElement()
   * @generated
   */
  void setReadableElement(ReadableEnum value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameters</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference.
   * @see #setParameters(Parameters)
   * @see org.xtext.selenium.eliedenis.eDdsl.EDdslPackage#getRead_Parameters()
   * @model containment="true"
   * @generated
   */
  Parameters getParameters();

  /**
   * Sets the value of the '{@link org.xtext.selenium.eliedenis.eDdsl.Read#getParameters <em>Parameters</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameters</em>' containment reference.
   * @see #getParameters()
   * @generated
   */
  void setParameters(Parameters value);

} // Read
