/**
 * generated by Xtext 2.12.0
 */
package org.xtext.selenium.eliedenis.eDdsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Series</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.selenium.eliedenis.eDdsl.Series#getBrowser <em>Browser</em>}</li>
 *   <li>{@link org.xtext.selenium.eliedenis.eDdsl.Series#getExpectedReturn <em>Expected Return</em>}</li>
 *   <li>{@link org.xtext.selenium.eliedenis.eDdsl.Series#getOperations <em>Operations</em>}</li>
 * </ul>
 *
 * @see org.xtext.selenium.eliedenis.eDdsl.EDdslPackage#getSeries()
 * @model
 * @generated
 */
public interface Series extends EObject
{
  /**
   * Returns the value of the '<em><b>Browser</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.selenium.eliedenis.eDdsl.BrowserEnum}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Browser</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Browser</em>' attribute.
   * @see org.xtext.selenium.eliedenis.eDdsl.BrowserEnum
   * @see #setBrowser(BrowserEnum)
   * @see org.xtext.selenium.eliedenis.eDdsl.EDdslPackage#getSeries_Browser()
   * @model
   * @generated
   */
  BrowserEnum getBrowser();

  /**
   * Sets the value of the '{@link org.xtext.selenium.eliedenis.eDdsl.Series#getBrowser <em>Browser</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Browser</em>' attribute.
   * @see org.xtext.selenium.eliedenis.eDdsl.BrowserEnum
   * @see #getBrowser()
   * @generated
   */
  void setBrowser(BrowserEnum value);

  /**
   * Returns the value of the '<em><b>Expected Return</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.selenium.eliedenis.eDdsl.BoolEnum}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expected Return</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expected Return</em>' attribute.
   * @see org.xtext.selenium.eliedenis.eDdsl.BoolEnum
   * @see #setExpectedReturn(BoolEnum)
   * @see org.xtext.selenium.eliedenis.eDdsl.EDdslPackage#getSeries_ExpectedReturn()
   * @model
   * @generated
   */
  BoolEnum getExpectedReturn();

  /**
   * Sets the value of the '{@link org.xtext.selenium.eliedenis.eDdsl.Series#getExpectedReturn <em>Expected Return</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expected Return</em>' attribute.
   * @see org.xtext.selenium.eliedenis.eDdsl.BoolEnum
   * @see #getExpectedReturn()
   * @generated
   */
  void setExpectedReturn(BoolEnum value);

  /**
   * Returns the value of the '<em><b>Operations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.selenium.eliedenis.eDdsl.Operation}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operations</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operations</em>' containment reference list.
   * @see org.xtext.selenium.eliedenis.eDdsl.EDdslPackage#getSeries_Operations()
   * @model containment="true"
   * @generated
   */
  EList<Operation> getOperations();

} // Series
