/**
 * generated by Xtext 2.12.0
 */
package org.xtext.selenium.eliedenis.eDdsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Set</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.selenium.eliedenis.eDdsl.VariableSet#getVarName <em>Var Name</em>}</li>
 *   <li>{@link org.xtext.selenium.eliedenis.eDdsl.VariableSet#getAction <em>Action</em>}</li>
 * </ul>
 *
 * @see org.xtext.selenium.eliedenis.eDdsl.EDdslPackage#getVariableSet()
 * @model
 * @generated
 */
public interface VariableSet extends ActionNoReturn
{
  /**
   * Returns the value of the '<em><b>Var Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Name</em>' attribute.
   * @see #setVarName(String)
   * @see org.xtext.selenium.eliedenis.eDdsl.EDdslPackage#getVariableSet_VarName()
   * @model
   * @generated
   */
  String getVarName();

  /**
   * Sets the value of the '{@link org.xtext.selenium.eliedenis.eDdsl.VariableSet#getVarName <em>Var Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Name</em>' attribute.
   * @see #getVarName()
   * @generated
   */
  void setVarName(String value);

  /**
   * Returns the value of the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Action</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' containment reference.
   * @see #setAction(ActionReturn)
   * @see org.xtext.selenium.eliedenis.eDdsl.EDdslPackage#getVariableSet_Action()
   * @model containment="true"
   * @generated
   */
  ActionReturn getAction();

  /**
   * Sets the value of the '{@link org.xtext.selenium.eliedenis.eDdsl.VariableSet#getAction <em>Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' containment reference.
   * @see #getAction()
   * @generated
   */
  void setAction(ActionReturn value);

} // VariableSet
