/**
 * generated by Xtext 2.12.0
 */
package org.xtext.selenium.eliedenis.generator;

@SuppressWarnings("all")
public class Counter {
  private int count;
  
  public int Counter() {
    return this.count = 0;
  }
  
  public int nextCount() {
    return this.count++;
  }
}
