/*
 * generated by Xtext 2.12.0
 */
package org.xtext.selenium.eliedenis.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.selenium.eliedenis.parser.antlr.internal.InternalEDdslParser;
import org.xtext.selenium.eliedenis.services.EDdslGrammarAccess;

public class EDdslParser extends AbstractAntlrParser {

	@Inject
	private EDdslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEDdslParser createParser(XtextTokenStream stream) {
		return new InternalEDdslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Test";
	}

	public EDdslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EDdslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
