/**
 * generated by Xtext 2.12.0
 */
package org.xtext.selenium.eliedenis;

import org.xtext.selenium.eliedenis.AbstractEDdslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class EDdslRuntimeModule extends AbstractEDdslRuntimeModule {
}
